Repository Flowminder/FlowKit, pull requests merged in 2022-04, with the labels that each got.

#5079 Bumps Black to 22.3.0
  .pre-commit-config.yaml
Labels: dependencies, CI, development

#5081 Re-lock Pipfiles
  autoflow/Pipfile.lock
  deployment/Pipfile.lock
  docs/Pipfile.lock
  flowapi/Pipfile
  flowapi/Pipfile.lock
  flowapi/setup.py
  flowauth/Pipfile.lock
  flowclient/Pipfile.lock
  flowdb/Pipfile.lock
  flowdb/testdata/synthetic_data/Pipfile.lock
  flowdb/testdata/test_data/Pipfile.lock
  flowdb/tests/Pipfile.lock
  flowetl/Pipfile.lock
  flowkit_jwt_generator/Pipfile.lock
  flowmachine/Pipfile.lock
  integration_tests/Pipfile.lock
Labels: dependencies, ready-to-merge, maintenance

#5093 Extend trigger to cover 'CREATE TABLE AS' commands
  CHANGELOG.md
  flowdb/bin/build/9000_last_create_roles.sh
Labels: FlowMachine, FlowDB, ready-to-merge
