Repository Flowminder/FlowKit, pull requests merged in 2022-03, with the labels that each got.

#4909 flowetl and flowdb dockerfile maintinence
  flowdb.Dockerfile
  flowetl.Dockerfile
Labels: bug, CI, ready-to-merge, docker, Needs Review

#4940 Upgrade airflow
  CHANGELOG.md
  development_environment
  docs/Pipfile.lock
  docs/source/administrator/deployment.md
  flowapi/flowapi/config.py
  flowetl.Dockerfile
  flowetl.Dockerfile.dockerignore
  flowetl/Pipfile
  flowetl/Pipfile.lock
  flowetl/deployment_example/defaults_flowkit.env
  flowetl/deployment_example/docker-stack-flowkit.yml
  flowetl/entrypoint.sh
  flowetl/flowetl/flowetl/mixins/fixed_sql_mixin.py
  flowetl/flowetl/flowetl/mixins/fixed_sql_with_params_mixin.py
  flowetl/flowetl/flowetl/mixins/wrapping_sql_mixin.py
  flowetl/flowetl/flowetl/operators/analyze_operator.py
  flowetl/flowetl/flowetl/operators/create_foreign_staging_table_operator.py
  flowetl/flowetl/flowetl/sensors/file_flux_sensor.py
  flowetl/flowetl/flowetl/util.py
  flowetl/flowetl/setup.py
  flowetl/init.sh
  flowetl/tests/integration/conftest.py
  flowetl/tests/integration/test_fixuid.py
  flowetl/tests/integration/test_security_setup.py
  flowetl/tests/unit/conftest.py
  flowetl/tests/unit/test_create_dag.py
  flowetl/tests/unit/test_fixed_sql_mixin.py
  flowetl/tests/unit/test_foreign_staging_table_operator.py
  flowetl/tests/unit/test_params_mixin.py
  flowetl/tests/unit/test_qa_check_discovery.py
  flowetl/tests/unit/test_wrapping_sql_mixin.py
Labels: ready-to-merge, FlowETL, Needs Review

#4948 Re-lock pipfiles
  autoflow/Pipfile
  autoflow/Pipfile.lock
  deployment/Pipfile.lock
  docs/Pipfile.lock
  flowapi/Pipfile.lock
  flowauth/Pipfile.lock
  flowclient/Pipfile.lock
  flowdb/Pipfile.lock
  flowdb/testdata/synthetic_data/Pipfile
  flowdb/testdata/synthetic_data/Pipfile.lock
  flowdb/testdata/test_data/Pipfile.lock
  flowdb/tests/Pipfile.lock
  flowetl/Pipfile
  flowetl/Pipfile.lock
  flowkit_jwt_generator/Pipfile.lock
  flowmachine/Pipfile
  flowmachine/Pipfile.lock
  flowmachine/tests/test_query_object_construction.test_construct_query.approved.txt
  integration_tests/Pipfile.lock
Labels: dependencies, ready-to-merge

#4975 Bump python dependencies
  autoflow/Pipfile.lock
  docs/Pipfile.lock
  flowapi/Pipfile.lock
  flowauth/Pipfile.lock
  flowclient/Pipfile.lock
  flowdb/testdata/test_data/Pipfile.lock
  flowdb/tests/Pipfile.lock
  flowetl/Pipfile.lock
  flowkit_jwt_generator/Pipfile.lock
  flowmachine/Pipfile.lock
  integration_tests/Pipfile.lock
  integration_tests/tests/query_tests/test_queries.py
Labels: dependencies, ready-to-merge

#4954 Non-blocking unstored dependencies graph
  CHANGELOG.md
  flowmachine/flowmachine/core/dependency_graph.py
  flowmachine/flowmachine/core/model_result.py
  flowmachine/flowmachine/core/query.py
  flowmachine/tests/test_dependency_graph.py
Labels: enhancement, FlowMachine, ready-to-merge

#5000 Housekeeping
  .github/dependabot.yml
  README.md
Labels: ready-to-merge

#5010 Re-lock Pipfiles
  autoflow/Pipfile.lock
  docs/Pipfile.lock
  flowapi/Pipfile.lock
  flowauth/Pipfile.lock
  flowclient/Pipfile.lock
  flowdb/Pipfile.lock
  flowdb/testdata/synthetic_data/Pipfile.lock
  flowdb/testdata/test_data/Pipfile.lock
  flowdb/tests/Pipfile.lock
  flowetl/Pipfile.lock
  flowkit_jwt_generator/Pipfile.lock
  flowmachine/Pipfile.lock
  integration_tests/Pipfile.lock
Labels: dependencies, ready-to-merge
