Repository Flowminder/FlowKit, pull requests merged in 2022-01, with the labels that each got.

#4646 CI config updates
  .circleci/config.yml
  autoflow/Gemfile.lock
Labels: CI, development, P-Now

#4770 Add a trigger to make cache tables owned by flowmachine
  CHANGELOG.md
  flowdb/bin/build/9000_last_create_roles.sh
Labels: FlowMachine, ready-to-merge, Needs Review

#4777 Fix explain
  CHANGELOG.md
  flowmachine/flowmachine/core/query.py
Labels: enhancement, FlowMachine, ready-to-merge
