Repository Flowminder/FlowKit, pull requests merged in 2022-05, with the labels that each got.

#5139 Bump Python dependencies
  autoflow/Pipfile.lock
  docs/Pipfile.lock
  flowapi/Pipfile.lock
  flowauth/Pipfile.lock
  flowclient/Pipfile.lock
  flowdb/Pipfile.lock
  flowdb/testdata/synthetic_data/Pipfile.lock
  flowdb/testdata/test_data/Pipfile.lock
  flowdb/tests/Pipfile.lock
  flowetl/Pipfile.lock
  flowkit_jwt_generator/Pipfile.lock
  flowmachine/Pipfile.lock
  integration_tests/Pipfile.lock
Labels: dependencies

#5152 Add pgdg apt-archive
  flowdb.Dockerfile
Labels: FlowDB, CI, ready-to-merge, docker

#5169 Bump python deps
  autoflow/Pipfile.lock
  docs/Pipfile.lock
  flowapi/Pipfile.lock
  flowauth/Pipfile.lock
  flowclient/Pipfile.lock
  flowdb/Pipfile.lock
  flowdb/testdata/synthetic_data/Pipfile.lock
  flowdb/testdata/test_data/Pipfile.lock
  flowdb/tests/Pipfile.lock
  flowetl/Pipfile.lock
  flowkit_jwt_generator/Pipfile.lock
  flowmachine/Pipfile.lock
  integration_tests/Pipfile.lock
Labels: dependencies

#5162 Bump postgres tag
  flowdb.Dockerfile
Labels: ready-to-merge

#5185 Bump python deps
  autoflow/Pipfile.lock
  deployment/Pipfile.lock
  docs/Pipfile.lock
  flowapi/Pipfile.lock
  flowauth/Pipfile.lock
  flowclient/Pipfile.lock
  flowdb/Pipfile.lock
  flowdb/testdata/synthetic_data/Pipfile.lock
  flowdb/testdata/test_data/Pipfile.lock
  flowdb/tests/Pipfile.lock
  flowetl/Pipfile.lock
  flowkit_jwt_generator/Pipfile.lock
  flowmachine/Pipfile.lock
  integration_tests/Pipfile.lock
Labels: dependencies

#4754 Use Union's ability to take variadic args
  flowmachine/flowmachine/core/union.py
  flowmachine/flowmachine/features/subscriber/day_trajectories.py
  flowmachine/flowmachine/features/subscriber/modal_location.py
  flowmachine/flowmachine/features/subscriber/total_active_periods.py
  flowmachine/tests/test_query_union.py
Labels: enhancement, FlowMachine, ready-to-merge
