Repository Flowminder/FlowKit, pull requests merged in 2023-01, with the labels that each got.

#5736 Bump deps
  .circleci/config.yml
  autoflow/Pipfile.lock
  deployment/Pipfile.lock
  docs/Pipfile.lock
  flowapi/Pipfile.lock
  flowauth/Pipfile.lock
  flowclient/Pipfile
  flowclient/Pipfile.lock
  flowdb/Pipfile.lock
  flowdb/testdata/synthetic_data/Pipfile.lock
  flowdb/testdata/test_data/Pipfile.lock
  flowdb/tests/Pipfile.lock
  flowetl/Pipfile.lock
  flowkit_jwt_generator/Pipfile.lock
  flowmachine/Pipfile.lock
  integration_tests/Pipfile.lock
Labels: dependencies

#5722 Changes to MajorityLocation
  CHANGELOG.md
  flowclient/flowclient/query_specs.py
  flowmachine/flowmachine/core/server/query_schemas/majority_location.py
  flowmachine/flowmachine/features/subscriber/majority_location.py
  flowmachine/tests/test_majority_location.py
  flowmachine/tests/test_mobility_classification.py
  flowmachine/tests/test_query_object_construction.py
  flowmachine/tests/test_query_object_construction.test_construct_query.approved.txt
  integration_tests/tests/flowapi_tests/test_api_spec.test_generated_openapi_json_spec.approved.txt
  integration_tests/tests/flowapi_tests/test_api_spec.test_generated_openapi_yaml_spec.approved.txt
  integration_tests/tests/flowmachine_server_tests/test_server.test_api_spec_of_flowmachine_query_schemas.approved.txt
  integration_tests/tests/query_tests/test_queries.py
Labels: FlowClient, FlowMachine, refactoring, ready-to-merge

#5737 Updating demo_scopes.json
  CHANGELOG.md
  docs/source/analyst/index.md
  flowauth/backend/flowauth/demo_data/demo_scopes.json
  flowauth/backend/flowauth/models.py
  flowauth/backend/tests/test_commands.py
Labels: FlowAuth, docs, ready-to-merge, quick-start-script

#5760 Bump Python dependencies
  autoflow/Pipfile.lock
  deployment/Pipfile.lock
  docs/Pipfile.lock
  flowapi/Pipfile.lock
  flowauth/Pipfile.lock
  flowclient/Pipfile.lock
  flowdb/Pipfile.lock
  flowdb/testdata/synthetic_data/Pipfile.lock
  flowdb/testdata/test_data/Pipfile.lock
  flowdb/tests/Pipfile.lock
  flowetl/Pipfile.lock
  flowkit_jwt_generator/Pipfile.lock
  flowmachine/Pipfile.lock
  integration_tests/Pipfile.lock
Labels: dependencies

#5762 Update CHANGELOG.md
  CHANGELOG.md
Labels: ready-to-merge

#5793 Bump Python deps
  autoflow/Pipfile.lock
  deployment/Pipfile.lock
  docs/Pipfile.lock
  flowapi/Pipfile.lock
  flowauth/Pipfile.lock
  flowclient/Pipfile.lock
  flowdb/Pipfile.lock
  flowdb/testdata/synthetic_data/Pipfile.lock
  flowdb/testdata/test_data/Pipfile.lock
  flowdb/tests/Pipfile.lock
  flowetl/Pipfile.lock
  flowkit_jwt_generator/Pipfile.lock
  flowmachine/Pipfile.lock
  integration_tests/Pipfile.lock
Labels: dependencies

#5816 Release 1.18.1
  CHANGELOG.md
Labels: ready-to-merge, release
