Repository Flowminder/FlowKit, pull requests merged in 2023-11, with the labels that each got.

#6385 Bump python deps
  autoflow/Pipfile.lock
  deployment/Pipfile.lock
  docs/Pipfile.lock
  flowapi/Pipfile.lock
  flowauth/Pipfile.lock
  flowclient/Pipfile.lock
  flowdb/Pipfile.lock
  flowdb/testdata/synthetic_data/Pipfile
  flowdb/testdata/synthetic_data/Pipfile.lock
  flowdb/testdata/test_data/Pipfile.lock
  flowdb/tests/Pipfile.lock
  flowetl.Dockerfile
  flowetl/.airflow-version
  flowetl/dev-requirements.txt
  flowetl/requirements.txt
  flowkit_jwt_generator/Pipfile.lock
  flowmachine/Pipfile.lock
  integration_tests/Pipfile.lock
Labels: dependencies

#6392 Add jwt generator wheel
  .circleci/config.yml
Labels: ready-to-merge

#6393 Bump python deps and Airflow
  .circleci/config.yml
  .github/workflows/codeql-analysis.yml
  docs/Pipfile.lock
  flowapi/Pipfile.lock
  flowauth/Pipfile.lock
  flowclient/Pipfile.lock
  flowdb/Pipfile.lock
  flowdb/testdata/synthetic_data/Pipfile.lock
  flowdb/testdata/test_data/Pipfile.lock
  flowdb/tests/Pipfile
  flowdb/tests/Pipfile.lock
  flowetl.Dockerfile
  flowetl/.airflow-version
  flowetl/dev-requirements.txt
  flowetl/requirements.txt
  flowkit_jwt_generator/Pipfile.lock
  flowmachine/Pipfile.lock
  integration_tests/Pipfile
  integration_tests/Pipfile.lock
Labels: dependencies

#6286 Adding flowpytertask to flowetl requirements
  flowetl/requirements.in
  flowetl/requirements.txt
  flowetl/tests/unit/test_qa_check_discovery.py
Labels: docker, FlowETL, Needs Review

#6406 Bump deps and pin base images
  docs/Pipfile.lock
  flowapi.Dockerfile
  flowapi/Pipfile.lock
  flowauth.Dockerfile
  flowauth/Pipfile.lock
  flowclient/Pipfile.lock
  flowdb/Pipfile.lock
  flowdb/testdata/synthetic_data/Pipfile.lock
  flowdb/testdata/test_data/Pipfile.lock
  flowdb/tests/Pipfile.lock
  flowetl/dev-requirements.txt
  flowetl/requirements.txt
  flowkit_jwt_generator/Pipfile.lock
  flowmachine.Dockerfile
  flowmachine/Pipfile.lock
  integration_tests/Pipfile.lock
Labels: FlowAuth, FlowMachine, FlowAPI, dependencies, ready-to-merge, docker

#6413 Bump deps
  docs/Pipfile.lock
  flowapi/Pipfile.lock
  flowauth/Pipfile.lock
  flowclient/Pipfile.lock
  flowdb/Pipfile.lock
  flowdb/testdata/synthetic_data/Pipfile.lock
  flowdb/testdata/test_data/Pipfile.lock
  flowdb/tests/Pipfile.lock
  flowetl/requirements.txt
  flowkit_jwt_generator/Pipfile.lock
  flowmachine.Dockerfile
  flowmachine/Pipfile.lock
  integration_tests/Pipfile.lock
Labels: dependencies
